repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: [cytoself, -t, py39, -S, -l, "120"]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--count, --max-complexity=15, --max-line-length=127, --statistics, cytoself]
